### PR TITLE
recaptcha: Use new APIs

### PR DESCRIPTION
**Pull request by kalaker**
Switch to Google's new APIs for reCAPTCHA which have better human
detection and make things harder for robots.

### CODE REVIEW

**Comment by kalaker** [comment]
Fixes issue #244

**Comment by kalaker** [comment]
You can see this change in action at: https://paste.teamblueridge.org

**Comment by kalaker** [comment]
This change uses the library now recommended by Google, updates all themes to the currently recommended method of displaying the new reCAPTCHA (as well as adding necessary JavaScript), and modifies the `_valid_recaptcha()` function to properly handle the new library.

**Comment by claudehohl** [comment]
There has already been a pull request (with simpler modifications): https://github.com/claudehohl/Stikked/pull/239/files

But thanks anyway for the contribution!

**Comment by SimonSickle** [comment]
These follow Google's standards better and are a lot cleaner. This commit simplifies future updates, too since an external library is utilized

**Pull request closed without merging**
