### PR TITLE
Add back Android logcat syntax highlighting support

### PR DESCRIPTION
**Pull request by mathur**
The php file was removed with commit 1e3515ae30a76356bc7d350bf4199391796c410f
Add it back

### CODE REVIEW

**Comment by PJanisio** [comment]
Dunno why new geshi version abandoned Logcat support, did you tested it and found working?

**Comment by kalaker** [comment]
I don't believe the geshi ever included logcat support. I remember that it was added in ce4f741.

**Comment by PJanisio** [comment]
Mhmmm this way.

**Comment by mathur** [comment]
I didn't test this code myself to be entirely honest; I just noticed the file was missing and tracked the deletion back to the commit I mentioned. However, I believe this should fix geshi logcat highlighting.

**Comment by PJanisio** [comment]
It works, not perfect, but still better than nothing :)

**Comment by claudehohl** [comment]
Thanks!

**Pull request merged**
