### PR TITLE
Rewrite docker setup

### PR DESCRIPTION
**Pull request by xrobau**
This now allows ANY Stikked configuration variable to be overridden by environment variables.

I also tidied up the Dockerfile a bit, and bumped the PHP version to 7.1 (... because why not!?)

The only operational change is that the cron job will ALWAYS run, and a random key is generated for it on every startup, if not specified.

### CODE REVIEW

**Comment by claudehohl** [comment]
Very nice!

Is there a reason why you named some vars "STIKKIT" (instead of "STIKKED")?

**Comment by xrobau** [comment]
Um. At a guess, I'm an idiot?  Sorry, I was half asleep when I was doing that 8)

**Comment by xrobau** [comment]
We can't go to PHP 7.2, as there's a function_create call in libraries/geshi, and there is no update to it yet

**Comment by tm1000** [comment]
@xrobau means "create_function" http://php.net/manual/en/function.create-function.php

**Comment by xrobau** [comment]
We're using this in production now, so it seems good to go, for me!

**Comment by claudehohl** [comment]
Alrighty, very nice. Thanks!

**Pull request merged**
