### PR TITLE
fixed reflected xss

### PR DESCRIPTION
**Pull request by Th3R3p0**
https://github.com/claudehohl/Stikked/issues/432

@medskill

### CODE REVIEW

**Comment by caylorme** [comment]
Reviewed. Approved

**Comment by claudehohl** [comment]
I need to test that first.

Also, there is a "hello" here: https://github.com/claudehohl/Stikked/pull/438/files#diff-7a07ec74f46b942a5165e46f3a922b77R3 - probably a leftover from debugging ;)

**Comment by Th3R3p0** [comment]
Yeah that hello was left over from debugging. i can take care of that later tonight, or if you beat me to it, feel free to remove it.

**Comment by claudehohl** [comment]
This was indeed an issue. Gosh, I should have reacted earlier. I first thought that CI filters by default, but now I remember that I had to turn global XSS-filtering off, because sometimes you just want to paste text containing <script>-tags.

Anyway, thanks for fixing!

**Pull request merged**
