### PR TITLE
Fixed 'embed code' in view paste for stikkedizr

### PR DESCRIPTION
**Pull request by PJanisio**
Click&hide embed code for stikkedizr didnt work returning in console
missing jQuery lib.
jquery lib name change is neccessary, dunno why. Root cause not found...

### CODE REVIEW

**Comment by PJanisio** [comment]
This PR needs additional comment:

Even if linkage to jquery-1.10.2.min.js is made right in footer.php, than jquery is not loaded in paste view. If you change only the file name from jquery-1.10.2.min.js -> jquery.js than it works, but it call in the browser console error about missing jquery lib on main page, wired.

To make it work you also need to truncate the static/asset directory.

**Comment by PJanisio** [comment]
@claudehohl 

What do you think about this PR? I do realize that it is not the root cause solving solution, but it works great - tested it on my pastebin site.

So close it or merge it :) It is up to you.

**Comment by xZero707** [comment]
Can you provide demo? I would like to see it in action. 
However, it's still @claudehohl decision to merge it or not to.

**Comment by PJanisio** [comment]
@xZero707 

Here you have paste view for my stikked site: http://pastebin.pl/view/fda81987
For comparison, switch your theme to stikkedizr and you will see that in your browser console you will get en error regarding jQuery library and due to that "Show code" does not work.

**Comment by xZero707** [comment]
I was unable to reproduce issue on my site which is running latest Stikked (from my repo) 
https://github.com/xZero707/Stikked

Demo: https://paste.elite7hackers.net/view/c13d99d7

**Comment by PJanisio** [comment]
Wired.

I reproduced this issue on two different servers ( localhost and pastebin.pl) running with not changed source from stikked master branch. I dont think it is possible to have the same misconfiguration in two machines :)

Did you deleted all files in static/asset directory before selecting stikkedizr theme?

**Comment by xZero707** [comment]
No I didn't, should I?

**Comment by PJanisio** [comment]
Yes. I`m curious about results :)

**Comment by PJanisio** [comment]
@xZero707 

And what is your feedback?

**Comment by xZero707** [comment]
Sorry, I have forgot, but I will test it out.

**Comment by PJanisio** [comment]
@xZero707 
Huh. I didnt see you reply.

Question is did you have clickable link: Show code like in example below, or your embedded code was already discovered after opening paste index? :)

image

**Comment by xZero707** [comment]
Nope, it was hidden. 
First I clicked link, then I took a screenshot.

I took screenshot in this order:
1. Load paste
2. Click on the link
3. Take screenshot
4. Open Stikked static folder
5. Take screenshot of 4.
6. Cut/Paste Window screenshot from 5. to 3.

I had to do this way since on 4., after browser window loses focus, Embed code immediately goes back to link.

**Comment by PJanisio** [comment]
@xZero707 

Thanks Aleksandar, closing PR. I have to look deeper at my machine configuration than.

**Pull request closed without merging**
