### PR TITLE
Added support for Goo.gl and Bit.ly URL shortening API-s

### PR DESCRIPTION
**Pull request by xZero707**
Managed to damage fork, don't ask how,, so I had to re-fork, commit and now reopen request. All code is up to date with current state of your repository. (2015/08/19 08:01PM)

Support for both mentioned API-s added, options in stikked.php.dist as well.
For users migrating from <0.9.2 (or whatever this version will be - decide your self and add appropriate changes), there is upgrade script which will prepare their application/config/stikked.php for new features, otherwise Stikked will fall back to legacy mode and they will be able to use only standard (yourls, gw.gd) API-s (until upgrade isn't done).
Upgrade script is safe to use, and will keep all options, however will ignore any custom code added by user. 
After successful upgrade, if there are write permission, script will add lock file and upgrade will be locked until mentioned file is removed.

Except Goog.gl and Bit.ly there is also "random" option which will make Stikked to chose randomly any properly set API and use it's URL shortening powers. This option may be a bit slow, so it's recommended that all API-s are filled up correctly. 
In latest commit there are possibility to chose which APIs will be considered in random mode.

### CODE REVIEW

**Comment by xZero707** [comment]
Fixed issue #295.

**Comment by claudehohl** [comment]
Uff, there is an upgrader... Not sure if this is a good idea. However, I'll merge it now and test it out by myself.

**Comment by xZero707** [comment]
Well, I didn't found any other solution since additional shortening API-s require additional entries in stikked.php file, so I tough upgrader script is better solution, otherwise people must add those entries them self. 
Do you have an idea for better solution?

And don't worry about compatibility, Stikked will fallback to legacy mode if those entries are not present, and everything will work like it does now.

**Comment by claudehohl** [comment]
I'm more worried about security. We have to mention that users delete that upload folder...

Anyway, thanks for your effort! I'm sifting through the issues and will test it later. Will be working on Stikked this week!

**Comment by xZero707** [comment]
You're welcome.

Upgrader will automatically lock it self after upgrade, however if there are no adequate permissions(chmod), that will fail, and user will be warned at end.
Upgrade may fail due to same problem (chmod).

For increased security maybe would be better to add lock file right ahead in upgrade folder, so user will have to remove lock file to unlock upgrader, however it will be more complicated for upgrade then.

**Comment by xZero707** [comment]
Another thing: It's not major security risk, since upgrader doesn't accept any input from user but: 
1. Utilize sample config file
2. Parse stikked.php file
3. In data from 1. append values from 2.
4. Lock upgrader

**Pull request merged**
