### PR TITLE
Added support for Goo.gl and Bit.ly URL shortening API-s

### PR DESCRIPTION
**Pull request by xZero707**
Support for both mentioned API-s added, options in stikked.php.dist as well.
For users migrating from <0.9.1 (or whatever this version will be - decide your self and add appropriate changes), there is upgrade script which will prepare their application/config/stikked.php for new features, otherwise Stikked will fall back to legacy mode  and  they will be able to use only standard (yourls, gw.gd) API-s (until upgrade isn't done).
Upgrade script is safe to use, and will keep all options, however will ignore any custom code added by user. 
After successful upgrade, if there are write permission, script will add lock file and upgrade will be locked until mentioned file is removed.

Except Goog.gl and Bit.ly there is also "random" option which will make Stikked to chose randomly any properly set API and use it's URL shortening powers. This option may be a bit slow, so it's recommended that all API-s are filled up correctly. 
In latest commit there are possibility to chose which APIs will be considered in random mode.

### CODE REVIEW

**Comment by claudehohl** [comment]
Woah epic!
Although I have to test it first in the next days. Stay tuned.

**Comment by xZero707** [comment]
Test it, I did (I always do) and seems to work properly, but as always unexpected bugs can occur.

**Comment by xZero707** [comment]
Make sure to check Goo.gl API. 
On my local it work, but on production server it doesn't. Same  OS, Apache and PHP version on both environments, so it's probably Googles delay with allowed IP addresses.

**Comment by xZero707** [comment]
@claudehohl - Any news so far?

**Comment by claudehohl** [comment]
Enjoying summer, been bathing for three days and off to a one week festival. So.. no news yet, sorry :/

**Comment by xZero707** [comment]
Ok, no problems :)

**Pull request closed without merging**
